name: Link Validator

permissions: {}

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron:  '0 6 * * 1'

jobs:
  validate-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # See https://github.com/actions/checkout/issues/299#issuecomment-677674415
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 100

      # temporarily disable git tag fetch (it fails because there are no tags)
      #- name: Fetch tags
      #  run: git fetch --depth=100 origin +refs/tags/*:refs/tags/*

      - name: Setup Java 8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6

      - name: Setup Coursier
        uses: coursier/setup-action@v1.3.3

      - name: Build Documentation
        run: |-
          sbt docs/paradox unidoc
        env:
          JAVA_OPTS: "-verbose:gc -Xmx4g"

      - name: Run Link Validator
        run: cs launch net.runne::site-link-validator:0.2.2 -- scripts/link-validator.conf
